import React from "react"
import { useContext } from "react"
import { assets } from "../assets/assets"
import { motion } from "motion/react"
import { AppContext } from "../context/AppContext"
import { useNavigate } from "react-router-dom"

const Header = () => {

  const {user, setShowLogin} = useContext(AppContext)
  const navigate = useNavigate()

  const onClickHandler = ()=>{
    if(user){
      navigate('/result')
    }else{
      setShowLogin(true)
    }
  }

  return (
    <motion.div className="flex flex-col justify-center 
    items-center text-center my-12 sm:my-16 md:my-20 lg:my-24 px-2"
      initial={{ opacity: 0, y: 50 }}
      transition={{ duration: 0.8 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
    >
      <motion.div className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-md border border-white/20 px-4 sm:px-6 py-1.5 sm:py-2 
      rounded-full text-white/90 text-xs sm:text-sm font-medium"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2, duration: 0.8 }}
      >
        <img src={assets.star_icon} alt="" className="w-3 h-3 sm:w-4 sm:h-4" />
        <p>Best AI Image Generator</p>
      </motion.div>

      <motion.h1 className="text-3xl xs:text-4xl sm:text-5xl md:text-6xl lg:text-7xl xl:text-8xl font-bold max-w-5xl
         mx-auto mt-6 sm:mt-8 md:mt-12 text-center leading-tight px-2">
        <span className="bg-gradient-to-r from-white via-purple-200 to-pink-200 bg-clip-text text-transparent">
          Turn Text to
        </span>
        <br />
        <span className="bg-gradient-to-r from-purple-400 via-pink-400 to-purple-400 bg-clip-text text-transparent animate-pulse">
          Stunning Images
        </span>
        <br />
        <span className="bg-gradient-to-r from-white via-purple-200 to-pink-200 bg-clip-text text-transparent">
          in Seconds
        </span>
      </motion.h1>

      <motion.p className="text-center max-w-2xl mx-auto mt-4 sm:mt-6 text-sm sm:text-base md:text-lg lg:text-xl text-white/70 leading-relaxed px-4"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4, duration: 0.8 }}
      >Unleash your creativity with AI. Transform your imagination into breathtaking visual art instantly
        - just describe your vision, and watch the magic happen.</motion.p>

      <motion.button 
        onClick={onClickHandler} 
        className="group relative mt-6 sm:mt-8 md:mt-10 lg:mt-12 text-sm sm:text-base md:text-lg text-white bg-gradient-to-r from-purple-600 to-pink-600 
        w-auto px-6 sm:px-8 md:px-12 py-3 sm:py-3.5 md:py-4 flex items-center gap-2 sm:gap-3 rounded-full font-semibold
        hover:shadow-2xl hover:shadow-purple-500/50 transition-all duration-300 overflow-hidden"
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ default: { duration: 0.5 }, opacity: { delay: 0.6, duration: 1 } }}
      >
        <span className="relative z-10 flex items-center gap-2">
          Generate Images
          <img className="h-4 w-4 sm:h-5 sm:w-5" src={assets.star_group} alt="" />
        </span>
        <div className="absolute inset-0 bg-gradient-to-r from-pink-600 to-purple-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
      </motion.button>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1}}
        transition={{ delay: 0.8, duration: 1 }}
        className="flex flex-wrap justify-center mt-12 sm:mt-16 md:mt-20 gap-3 sm:gap-4 md:gap-6 px-2">
        {Array(6).fill('').map((item, index) => (
          <motion.div
            key={index}
            whileHover={{ scale: 1.1, rotate: 2 }}
            className="relative group"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg blur opacity-0 group-hover:opacity-50 transition-opacity"></div>
            <img 
              className="relative rounded-lg border-2 border-white/20 hover:border-purple-400/50 transition-all duration-300
                         cursor-pointer shadow-xl w-12 h-12 xs:w-14 xs:h-14 sm:w-16 sm:h-16 md:w-20 md:h-20 lg:w-24 lg:h-24 object-cover"
              src={index % 2 === 0 ? assets.sample_img_2 : assets.sample_img_1}
              alt="" 
            />
          </motion.div>
        ))}
      </motion.div>

      <motion.p 
       initial={{ opacity: 0}}
       animate={{ opacity: 1}}
       transition={{ delay: 1, duration: 0.8 }}
      className="mt-4 sm:mt-6 text-white/50 text-xs sm:text-sm px-2">✨ Generated by TextToImage AI</motion.p>
    </motion.div>
  )
}

export default Header
